### ISSUE TITLE
[Tracking] Further Roadmap.

### ISSUE THREAD

**Issue by 7086cmd** [zvms/zvms4-frontend#22]
To enhance the user experience, a roadmap for the upcoming school year has been established (I may not actively participate in its development).

### Remove Unnecessary Functionalities

- [x] #23
- [x] #25
- ~~Remove the expand block from the activity list.~~

### Enhance User Interface

- [x] ~~Add the impression-unwritten activity list to the home page as a card.~~ Impression is not longer supported.
- [x] Merge the description page and the impression-writing page.
- [x] #28
- [x] #29

### Further Refinement

- ~~Separate the `activity` and `volunteer` entities:~~
   - `activity`: organized and pre-audited by school officials, with groups, and requires an impression;
   - `volunteer`: the temporary volunteer activity does not require an impression;
   - `special`: formerly a special activity.
- [x] Refine the create page.
- [x] Refine the management page.

### Rust client

This is a prototype that serves as the impetus for the addition of the `tauri` repository. In the Rust client, users can directly access FTP and other services on campus.
